import argparse
import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import cv2
import numpy as np
import torch
from PIL import Image

from ultralytics import YOLO


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run YOLOFuse local detection and use a local VLM to assess sea-surface obstacles."
    )
    parser.add_argument(
        "--weights",
        type=str,
        default="runs/train/boat-dual-depth4/weights/best.pt",
        help="Path to YOLOFuse weights.",
    )
    parser.add_argument(
        "--source",
        type=str,
        default="ultralytics/assets/LLVIP/images/image.png",
        help="Input source accepted by YOLO/Ultralytics.",
    )
    parser.add_argument("--device", type=str, default="0", help="Inference device, e.g. 0 or cpu.")
    parser.add_argument("--imgsz", type=int, default=640, help="Inference size.")
    parser.add_argument("--iou", type=float, default=0.45, help="NMS IoU threshold.")
    parser.add_argument(
        "--yolo-conf-min",
        type=float,
        default=0.2,
        help="Ignore detections below this confidence as noise.",
    )
    parser.add_argument(
        "--yolo-known-conf",
        type=float,
        default=0.7,
        help="Confidence threshold above which YOLO detections are treated as reliable detections.",
    )
    parser.add_argument(
        "--vlm-trigger-gap",
        type=int,
        default=15,
        help="Minimum number of frames between VLM requests.",
    )
    parser.add_argument(
        "--max-candidates",
        type=int,
        default=5,
        help="Maximum number of low-confidence candidate boxes included in the VLM prompt.",
    )
    parser.add_argument(
        "--known-classes",
        type=str,
        default="",
        help="Comma-separated known classes. Defaults to the model names.",
    )
    parser.add_argument(
        "--vlm-model",
        type=str,
        default="Qwen/Qwen2.5-VL-3B-Instruct",
        help="Local Hugging Face VLM model id or path.",
    )
    parser.add_argument(
        "--vlm-device",
        type=str,
        default="auto",
        help="Local VLM device map, e.g. auto, cuda:0, cpu.",
    )
    parser.add_argument(
        "--vlm-max-new-tokens",
        type=int,
        default=256,
        help="Maximum new tokens generated by the local VLM.",
    )
    parser.add_argument(
        "--save-dir",
        type=str,
        default="runs/vlm_unknown",
        help="Directory to save annotated frames and JSONL logs.",
    )
    parser.add_argument(
        "--motion-diff-threshold",
        type=float,
        default=12.0,
        help="Pixel diff threshold for motion trigger when YOLO has no response.",
    )
    parser.add_argument(
        "--depth-max-distance",
        type=float,
        default=30.0,
        help="Trigger VLM when the paired depth map contains an object within this distance.",
    )
    parser.add_argument(
        "--depth-value-scale",
        type=float,
        default=1.0,
        help="Scale factor to convert raw depth-map values to meters.",
    )
    parser.add_argument(
        "--crop-pad",
        type=int,
        default=24,
        help="Extra padding around triggered regions before cropping RGB for VLM.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display frames in a local OpenCV window.",
    )
    return parser.parse_args()


def clamp_box(box: List[float], width: int, height: int) -> List[int]:
    x1, y1, x2, y2 = box
    x1 = max(0, min(int(round(x1)), width - 1))
    y1 = max(0, min(int(round(y1)), height - 1))
    x2 = max(0, min(int(round(x2)), width - 1))
    y2 = max(0, min(int(round(y2)), height - 1))
    return [x1, y1, x2, y2]


class LocalQwenVLClient:
    def __init__(self, model_name: str, device: str = "auto", max_new_tokens: int = 256):
        try:
            from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration
        except ImportError as exc:
            raise RuntimeError(
                "Missing local VLM dependencies. Install: pip install torch transformers accelerate pillow"
            ) from exc

        self.model_name = model_name
        self.max_new_tokens = max_new_tokens
        self.processor = AutoProcessor.from_pretrained(model_name)

        load_kwargs: Dict[str, Any] = {"torch_dtype": torch.float16 if torch.cuda.is_available() else torch.float32}
        if device == "auto":
            load_kwargs["device_map"] = "auto"
            self.runtime_device = None
        elif device.startswith("cuda") or device == "cpu":
            self.runtime_device = device
        else:
            load_kwargs["device_map"] = "auto"
            self.runtime_device = None

        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(model_name, **load_kwargs)
        if self.runtime_device is not None:
            self.model = self.model.to(self.runtime_device)

    def validate_detection(
        self,
        frame_bgr: np.ndarray,
        yolo_label: str,
        yolo_confidence: float,
    ) -> Dict[str, Any]:
        frame_h, frame_w = frame_bgr.shape[:2]
        prompt = self._build_prompt(frame_w, frame_h, yolo_label, yolo_confidence)
        image = Image.fromarray(cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB))
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": prompt},
                ],
            }
        ]
        text = self.processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        inputs = self.processor(text=[text], images=[image], return_tensors="pt")
        target_device = self.runtime_device or self.model.device
        inputs = {k: v.to(target_device) if hasattr(v, "to") else v for k, v in inputs.items()}
        with torch.inference_mode():
            generated_ids = self.model.generate(**inputs, max_new_tokens=self.max_new_tokens)
        trimmed = generated_ids[:, inputs["input_ids"].shape[1] :]
        content = self.processor.batch_decode(
            trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]
        parsed = self._parse_json(content)
        return {
            "is_confirmed": bool(parsed.get("is_confirmed", False)),
            "type": parsed.get("type"),
            "type_en": str(parsed.get("type_en", ""))[:32],
            "must_avoid": bool(parsed.get("must_avoid", False)),
            "threat_level": parsed.get("threat_level"),
            "confidence": float(parsed.get("confidence", 0.0)),
            "reason": str(parsed.get("reason", ""))[:40],
            "image_size": [frame_w, frame_h],
        }

    @staticmethod
    def _parse_json(text: str) -> Dict[str, Any]:
        text = text.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if len(lines) >= 3:
                text = "\n".join(lines[1:-1]).strip()
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end < start:
            raise RuntimeError(f"VLM returned non-JSON content: {text[:200]}")
        return json.loads(text[start : end + 1])

    @staticmethod
    def _build_prompt(
        frame_w: int,
        frame_h: int,
        yolo_label: str,
        yolo_confidence: float,
    ) -> str:
        return f"""
你是无人帆船的障碍物判断助手。

图像尺寸：宽 {frame_w}，高 {frame_h}。
YOLOFuse 预测类别：{yolo_label}
YOLOFuse 预测置信度：{yolo_confidence:.2f}

规则只有一条：
水面上任何有实体的物体，无人帆船都必须绕开，
不管它是船、木头、浮标还是其他任何东西。

must_avoid 判断标准：
- 水面上有实体物体 -> true
- 只有水面波纹、倒影、天空、远处陆地 -> false

请严格按照以下JSON格式返回，不要有其他文字：
{{
  "type": "物体的真实描述",
  "type_en": "english object label",
  "must_avoid": true,
  "threat_level": "高/中/低",
  "confidence": 0.0,
  "reason": "判断理由"
}}
""".strip()


def result_to_detections(result, known_conf: float, candidate_conf: float, max_candidates: int) -> Dict[str, List[Dict[str, Any]]]:
    known: List[Dict[str, Any]] = []
    candidates: List[Dict[str, Any]] = []
    if result.boxes is None:
        return {"known": known, "candidates": candidates}

    boxes = result.boxes.xyxy.cpu().numpy()
    confs = result.boxes.conf.cpu().numpy()
    classes = result.boxes.cls.cpu().numpy().astype(int)
    for box, conf, cls_id in zip(boxes, confs, classes):
        item = {
            "name": result.names[int(cls_id)],
            "confidence": float(conf),
            "bbox": [int(round(v)) for v in box.tolist()],
        }
        if conf >= known_conf:
            known.append(item)
        elif conf >= candidate_conf:
            candidates.append(item)

    candidates.sort(key=lambda x: x["confidence"])
    return {"known": known, "candidates": candidates[:max_candidates]}


def resolve_depth_path(rgb_path: str) -> Path:
    return Path(str(rgb_path).replace("/images/", "/imagesIR/"))


def load_depth_map(rgb_path: str) -> Optional[np.ndarray]:
    depth_path = resolve_depth_path(rgb_path)
    if not depth_path.exists():
        return None
    return cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)


def boxes_intersect(a: List[int], b: List[int]) -> bool:
    return not (a[2] < b[0] or b[2] < a[0] or a[3] < b[1] or b[3] < a[1])


def pad_box(box: List[int], image_shape: tuple[int, int, int], pad: int) -> List[int]:
    height, width = image_shape[:2]
    x1, y1, x2, y2 = box
    return [max(0, x1 - pad), max(0, y1 - pad), min(width - 1, x2 + pad), min(height - 1, y2 + pad)]


def crop_region(image: np.ndarray, box: List[int]) -> np.ndarray:
    x1, y1, x2, y2 = box
    return image[y1 : y2 + 1, x1 : x2 + 1].copy()


def relative_boxes(boxes: List[Dict[str, Any]], crop_box: List[int]) -> List[Dict[str, Any]]:
    x0, y0, _, _ = crop_box
    cropped: List[Dict[str, Any]] = []
    for item in boxes:
        if not boxes_intersect(item["bbox"], crop_box):
            continue
        x1, y1, x2, y2 = item["bbox"]
        clone = dict(item)
        clone["bbox"] = [x1 - x0, y1 - y0, x2 - x0, y2 - y0]
        cropped.append(clone)
    return cropped


def depth_trigger_box(
    depth_map: Optional[np.ndarray],
    known: List[Dict[str, Any]],
    max_distance: float,
    value_scale: float,
    min_area: int = 120,
) -> Optional[List[int]]:
    if depth_map is None:
        return None
    depth = depth_map[..., 0] if depth_map.ndim == 3 else depth_map
    depth = depth.astype(np.float32) * value_scale
    valid = depth > 0
    near_mask = np.logical_and(valid, depth <= max_distance).astype(np.uint8) * 255
    if near_mask.max() == 0:
        return None
    contours, _ = cv2.findContours(near_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in sorted(contours, key=cv2.contourArea, reverse=True):
        if cv2.contourArea(contour) < min_area:
            continue
        x, y, w, h = cv2.boundingRect(contour)
        box = [x, y, x + w, y + h]
        if any(boxes_intersect(item["bbox"], box) for item in known):
            continue
        return box
    return None


def motion_trigger_box(
    previous_frame: Optional[np.ndarray],
    current_frame: np.ndarray,
    known: List[Dict[str, Any]],
    threshold: float,
    min_area: int = 120,
) -> Optional[List[int]]:
    if previous_frame is None or previous_frame.shape != current_frame.shape:
        return None
    prev_gray = cv2.cvtColor(previous_frame, cv2.COLOR_BGR2GRAY)
    curr_gray = cv2.cvtColor(current_frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(prev_gray, curr_gray)
    _, binary = cv2.threshold(diff, threshold, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in sorted(contours, key=cv2.contourArea, reverse=True):
        if cv2.contourArea(contour) < min_area:
            continue
        x, y, w, h = cv2.boundingRect(contour)
        box = [x, y, x + w, y + h]
        if any(boxes_intersect(item["bbox"], box) for item in known):
            continue
        return box
    return None


def pretty_write(path: Path, records: List[Dict[str, Any]]) -> None:
    path.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")


def draw_box(image: np.ndarray, bbox: List[int], label: str, color: tuple) -> None:
    x1, y1, x2, y2 = bbox
    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
    cv2.putText(
        image,
        label,
        (x1, max(20, y1 - 6)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        color,
        2,
        cv2.LINE_AA,
    )


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def main() -> None:
    args = parse_args()
    save_dir = Path(args.save_dir)
    ensure_dir(save_dir)
    frame_dir = save_dir / "frames"
    ensure_dir(frame_dir)
    log_path = save_dir / "events.jsonl"
    pretty_log_path = save_dir / "events_pretty.json"

    model = YOLO(args.weights)
    vlm_client: Optional[LocalQwenVLClient] = None
    try:
        vlm_client = LocalQwenVLClient(
            model_name=args.vlm_model,
            device=args.vlm_device,
            max_new_tokens=args.vlm_max_new_tokens,
        )
    except Exception as exc:  # noqa: BLE001
        print(f"Local VLM disabled: {exc}. Running YOLO-only mode.")

    frame_idx = 0
    pretty_records: List[Dict[str, Any]] = []

    stream = model.predict(
        source=args.source,
        stream=True,
        imgsz=args.imgsz,
        conf=args.yolo_conf_min,
        iou=args.iou,
        show=False,
        save=False,
        verbose=False,
        device=args.device,
    )

    with log_path.open("a", encoding="utf-8") as log_file:
        for result in stream:
            frame = result.orig_img.copy()
            depth_map = load_depth_map(str(result.path))
            parsed = result_to_detections(
                result=result,
                known_conf=args.yolo_known_conf,
                candidate_conf=args.yolo_conf_min,
                max_candidates=args.max_candidates,
            )
            known = parsed["known"]
            candidates = parsed["candidates"]
            yolo_detections = known + candidates
            trigger_regions: List[Dict[str, Any]] = [
                {
                    "reason": "yolo_detection_validation",
                    "bbox": item["bbox"],
                    "source": item,
                }
                for item in yolo_detections
            ]

            depth_trigger = None
            if len(yolo_detections) == 0:
                depth_trigger = depth_trigger_box(
                    depth_map=depth_map,
                    known=[],
                    max_distance=args.depth_max_distance,
                    value_scale=args.depth_value_scale,
                )
                if depth_trigger is not None:
                    trigger_regions.append(
                        {"reason": "depth_within_30m_without_yolo", "bbox": depth_trigger, "source": None}
                    )

            vlm_results: List[Dict[str, Any]] = []
            if vlm_client is not None:
                for trigger in trigger_regions:
                    source_item = trigger["source"]
                    try:
                        crop_box = pad_box(trigger["bbox"], frame.shape, args.crop_pad)
                        if source_item is not None:
                            vlm_result = vlm_client.validate_detection(
                                frame_bgr=crop_region(frame, crop_box),
                                yolo_label=source_item["name"],
                                yolo_confidence=source_item["confidence"],
                            )
                        else:
                            vlm_result = {
                                "is_confirmed": False,
                                "type": None,
                                "type_en": "depth-trigger",
                                "must_avoid": False,
                                "threat_level": None,
                                "confidence": 0.0,
                                "reason": "depth trigger only",
                                "image_size": [crop_box[2] - crop_box[0] + 1, crop_box[3] - crop_box[1] + 1],
                            }
                        vlm_result["trigger_reason"] = trigger["reason"]
                        vlm_result["crop_box"] = crop_box
                        if source_item is not None:
                            vlm_result["yolo_name"] = source_item["name"]
                            vlm_result["yolo_confidence"] = source_item["confidence"]
                        vlm_results.append(vlm_result)
                    except Exception as exc:  # noqa: BLE001
                        print(f"[frame {frame_idx}] VLM skipped: {exc}")

            for vlm_result in vlm_results:
                print("\n解析结果：")
                print(f"  触发原因：{vlm_result['trigger_reason']}")
                if "yolo_name" in vlm_result:
                    print(f"  YOLOFuse输出：{vlm_result['yolo_name']} {vlm_result['yolo_confidence']:.2f}")
                print(f"  真实物体：{vlm_result['type']}")
                print(f"  是否必须绕开：{vlm_result['must_avoid']}")
                print(f"  威胁等级：{vlm_result['threat_level']}")
                print(f"  置信度：{vlm_result['confidence']}")
                print(f"  理由：{vlm_result['reason']}")
                if vlm_result["must_avoid"]:
                    draw_box(
                        frame,
                        vlm_result["crop_box"],
                        str(vlm_result["type_en"] or "object"),
                        (0, 128, 255),
                    )

            stamp = {
                "frame_idx": frame_idx,
                "path": str(result.path),
                "depth_path": str(resolve_depth_path(str(result.path))),
                "known": known,
                "candidates": candidates,
                "yolo_detections": yolo_detections,
                "trigger_regions": trigger_regions,
                "vlm_results": vlm_results,
                "ts": time.time(),
            }
            log_file.write(json.dumps(stamp, ensure_ascii=False) + "\n")
            log_file.flush()
            pretty_records.append(stamp)
            pretty_write(pretty_log_path, pretty_records)

            output_path = frame_dir / f"frame_{frame_idx:06d}.jpg"
            cv2.imwrite(str(output_path), frame)

            if args.show:
                cv2.imshow("YOLOFuse + VLM Unknown Objects", frame)
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    break

            frame_idx += 1

    if args.show:
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
